---
title: "FY21 Projection Accuracy"
output: html_document
---
  
```{r setup, include=FALSE}
library(tidyverse)
library(rio)
library(bookHelpers)
library(kableExtra)
library(ggplot2)
library(assertthat)

knitr::opts_chunk$set(echo = FALSE)
last_year <- import("G:/Analyst Folders/Lillian/exp_projection_year/projections/quarterly_outputs/archive/FY21 Q3 Projection.xlsx")

expend <- import("G:/Fiscal Years/Fiscal 2021/Projections Year/2. Monthly Expenditure Data/Month 12_June Projections/Expenditure 2021-06_Run_9.xlsx") %>%
  filter(!is.na(`Agency ID`),
         `Fund Name` == "General") %>% 
  mutate_at(vars(ends_with("ID")), as.character)

totals <- expend %>%
  summarize_at(vars(c(`Total Budget`, `BAPS YTD EXP`)), sum, na.rm = TRUE) %>%
  rename(`FY21 Total Budget` = `Total Budget`, `FY21 Actual` = `BAPS YTD EXP`)

proj <- list(
  q1 = import("G:/Analyst Folders/Lillian/exp_projection_year/projections/quarterly_outputs/archive/FY21 Q1 Projection.xlsx"),
  q2 = import("G:/Analyst Folders/Lillian/exp_projection_year/projections/quarterly_outputs/archive/FY21 Q2 Projection.xlsx"),
  q3 = import("G:/Analyst Folders/Lillian/exp_projection_year/projections/quarterly_outputs/archive/FY21 Q3 Projection.xlsx")) %>%
  map(mutate_at, vars(ends_with("ID")), as.character) %>%
  map(group_by, `Agency Name`, `Object ID`)

proj$q1 <- proj$q1 %>%
  summarize(`Q1 Projection` = sum(`Q1 Projection`, na.rm = TRUE))
proj$q2 <- proj$q2 %>%
  summarize(`Q2 Projection` = sum(`Q2 Projection`, na.rm = TRUE))
proj$q3 <- proj$q3 %>%
  summarize(`Q3 Projection` = sum(`Q3 Projection`, na.rm = TRUE))

proj$final <- proj$q1 %>%
  full_join(proj$q2) %>%
  full_join(proj$q3)

projections <- expend %>%
  group_by(`Agency Name`, `Object ID`, `Object Name`) %>%
  summarize_at(vars(`Total Budget`, `BAPS YTD EXP`, starts_with("Q")), sum, na.rm = TRUE) %>%
  rename(`FY21 Total Budget` = `Total Budget`, `FY21 Actual` = `BAPS YTD EXP`) %>%
  left_join(proj$final) %>%
  mutate_if(is.numeric, replace_na, 0) %>%
  mutate(
    `Q1 Difference` = `Q1 Projection` - `FY21 Actual`,
    `Q2 Difference` = `Q2 Projection` - `FY21 Actual`,
    `Q3 Difference` = `Q3 Projection` - `FY21 Actual`) %>%
  ungroup() %>%
  unite(col = "Object",  c(`Object ID`, `Object Name`), sep = " ")

prep_data <- function(df, type) {
  
  if (type != "Citywide") {
    group <- c("FY21 Total Budget", "FY21 Actual", NULL, type)
    
    df <- df %>%
      group_by_at(type) %>%
      summarize_if(is.numeric, sum, na.rm = TRUE) 
    
  } else {
    group <- c("FY21 Total Budget", "FY21 Actual")
    
    df <- df %>%
      summarize_if(is.numeric, sum, na.rm = TRUE) 
  }
  
  df <- df %>%
    pivot_longer(starts_with("Q")) %>%
    separate(name, into = c("Quarter", "Type"), sep = " ", extra = "merge") %>%
    pivot_wider(names_from = "Type", values_from = "value") %>%
    bind_total_row(total_col = "Quarter", total_name = "Avg.", 
                   group_col = c("FY21 Total Budget", "FY21 Actual", group)) %>%
    mutate(Projection = ifelse(Quarter == "Avg.", Projection / 3, Projection),
           Difference = ifelse(Quarter == "Avg.", Difference / 3, Difference),
           `Percent Change` = Difference / `FY21 Actual`)
  
  if (type != "Citywide") {
    df <- df %>%
      arrange(!!sym(type))
  }
  
  check <- df %>%
    filter(Quarter == "Avg.") %>%
    summarize_at(vars(`FY21 Total Budget`, `FY21 Actual`), sum, na.rm = TRUE)
  
  assert_that(check$`FY21 Total Budget` == totals$`FY21 Total Budget`,
              check$`FY21 Actual` == totals$`FY21 Actual`)
  
  return(df)
}

make_pyramid_chart <- function(df, type) {
  df %>%
    ggplot(aes(x = Quarter, y = `Percent Change`, color = `Percent Change`)) + 
    geom_bar(stat = "identity") +
    # geom_text(aes(label = Quarter), size = 3, hjust = 1) +
    facet_wrap(as.formula(paste0("~`", type, "`")), ncol = 1) +
    scale_y_continuous(
      limits = c(-.25, 1.25), breaks = seq(-.25, .25, .05),
      labels = c("Projected lower", "-20%", "-15%", "-10%", "-5%", "0%",
                 "5%", "10%", "15%", "20%", "Projected higher"),
      sec.axis = dup_axis(),
      guide = guide_axis(angle = -45)) +
    geom_hline(yintercept = 0, color = "#69B34C", size = 1.2) +
    geom_hline(yintercept = c(-.04, .04), color = "#EFB700", size = 1.2) +
    geom_hline(yintercept = c(-.11, .11), color = "#FF0D0D", size = 1.2) +
    coord_flip(ylim = c(-.25, .25)) +
    theme_minimal() +
    theme(axis.line.x = element_line(arrow = grid::arrow(length = unit(0.3, "cm"), 
                                                         ends = "both")),
          axis.title.x = element_text(angle = 0),
          plot.margin = margin(0, 50, 0, 0))
}

```

- <span style="color: #69B34C;">**High accuracy**</span>: 1-3%
- <span style="color: #EFB700;">**Medium accuracy**</span>: 4-10%
- <span style="color: #FF0D0D;">**Low accuracy**</span>: 11%+
  
## Citywide accuracy
  
```{r citywide}

output <- prep_data(projections, "Citywide")

output %>%
  mutate(`Percent Change` = scales::percent(`Percent Change`, accuracy = 0.01),
         # using cell_spec instead of column_spec to set the background color bc the latter
         # colors the whole background, which is overwhelming
         `Percent Change` = cell_spec(`Percent Change`, 'html', color = "white", bold = TRUE,
                                      background= 
                                        case_when(abs(output$`Percent Change`) < .04 ~ "#69B34C",
                                                  abs(output$`Percent Change`) > .11 ~ "#FF0D0D",
                                                  TRUE ~ "#EFB700"))) %>%
  format_table_numbers() %>%
  format_table(total = TRUE, escape = FALSE) %>%
  collapse_rows(1:3, latex_hline = "major", valign = "top") 

```


## Object accuracy

Overall object accuracy is based on the percent change between the average of the `Projection` over all 3 quarters and the `FY21 Actual`.

```{r object, fig.height=10, fig.width=7, fig.align='center'}

output <- prep_data(projections, "Object")

make_pyramid_chart(output, "Object")

```

```{r}
output %>%
  mutate(`Percent Change` = scales::percent(`Percent Change`, accuracy = 0.01),
         # using cell_spec instead of column_spec to set the background color bc the latter
         # colors the whole background, which is overwhelming
         `Percent Change` = cell_spec(`Percent Change`, 'html', color = "white",  bold = TRUE,
                                      background= 
                                        case_when(abs(output$`Percent Change`) < .04 ~ "#69B34C",
                                                  abs(output$`Percent Change`) > .11 ~ "#FF0D0D",
                                                  TRUE ~ "#EFB700")),
         Object = cell_spec(Object, 'html', color = "white",  bold = TRUE,
                            background= 
                              case_when(abs(output$`Percent Change`) < .04 ~ "#69B34C",
                                        abs(output$`Percent Change`) > .11 ~ "#FF0D0D",
                                        TRUE ~ "#EFB700"))) %>%
  format_table_numbers() %>%
  format_table(total = TRUE, align = c("l", "l", rep("r", "5")), escape = FALSE) %>%
  row_spec(which(output$Quarter == "Avg."), bold = TRUE) %>%
  collapse_rows(1:4, latex_hline = "major", valign = "top") 
```


## Agency accuracy

Overall agency accuracy is based on the percent change between the average of the `Projection` over all 3 quarters and the `FY21 Actual`.

```{r agency, fig.height=50, fig.width=7, fig.align='center'}

output <- prep_data(projections, "Agency Name")

make_pyramid_chart(output, "Agency Name")
```


```{r agency table}
output %>%
  mutate(`Percent Change` = scales::percent(`Percent Change`, accuracy = 0.01),
         # using cell_spec instead of column_spec to set the background color bc the latter
         # colors the whole background, which is overwhelming
         `Percent Change` = cell_spec(`Percent Change`, 'html', color = "white",  bold = TRUE,
                                      background= 
                                        case_when(abs(output$`Percent Change`) < .04 ~ "#69B34C",
                                                  abs(output$`Percent Change`) > .11 ~ "#FF0D0D",
                                                  TRUE ~ "#EFB700")),
         `Agency Name` = cell_spec(`Agency Name`, 'html', color = "white",  bold = TRUE,
                            background= 
                              case_when(abs(output$`Percent Change`) < .04 ~ "#69B34C",
                                        abs(output$`Percent Change`) > .11 ~ "#FF0D0D",
                                        TRUE ~ "#EFB700"))) %>%
  format_table_numbers() %>%
  format_table(total = TRUE, align = c("l", "l", rep("r", "5")), escape = FALSE) %>%
  row_spec(which(output$Quarter == "Avg."), bold = TRUE) %>%
  collapse_rows(1:4, latex_hline = "major", valign = "top") 

```
